# Generated by Django 4.0.6 on 2023-02-24 13:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_floors', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('no_of_elevators', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_floor', models.PositiveIntegerField(default=0)),
                ('working_status', models.CharField(choices=[('maintenance', 'maintenance'), ('not working', 'not working'), ('working', 'working')], default='working', max_length=15)),
                ('last_service_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('elevator_system_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevatorSystem.elevatorsystem')),
            ],
        ),
    ]
