# Generated by Django 4.0.6 on 2023-02-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevatorSystem', '0002_elevator_door_status_elevator_motion_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevator',
            old_name='elevator_system_id',
            new_name='elevator_system',
        ),
    ]
