# Generated by Django 4.0.6 on 2023-02-26 05:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elevatorSystem', '0003_rename_elevator_system_id_elevator_elevator_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='next_destination_floor',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='ElevatorSystemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_floor', models.IntegerField()),
                ('request_status', models.CharField(choices=[('open', 'open'), ('close', 'close')], default='open', max_length=5)),
                ('reqyested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('elevator_system', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='elevatorSystem.elevatorsystem')),
            ],
        ),
    ]
