# Generated by Django 4.0.6 on 2023-02-26 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevatorSystem', '0004_elevator_next_destination_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevatorsystemrequest',
            name='elevator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='elevatorSystem.elevator'),
        ),
    ]
